spring:
  application:
    name: movies
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true

logging:
  level:
    org:
      springframework: DEBUG

server:
  servlet:
    context-path: /api/v1